version: "3.7"

services:
  pg:
    image: bitnami/postgresql:11-debian-9
    container_name: pg
    environment:
      POSTGRESQL_USERNAME: test
      POSTGRESQL_PASSWORD: test
      POSTGRESQL_DATABASE: test
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
